export const translateProvinceAbbrevation = (province: string): string => {
  const provinceTranslations: Record<string, string> = {
    AG: "Agrigento",
    AL: "Alessandria",
    AN: "Ancona",
    AO: "Aosta",
    AR: "Arezzo",
    AP: "Ascoli Piceno",
    AT: "Asti",
    AV: "Avellino",
    BA: "Bari",
    BL: "Belluno",
    BN: "Benevento",
    BG: "Bergamo",
    BI: "Biella",
    BO: "Bologna",
    BZ: "Bolzano",
    BS: "Brescia",
    BR: "Brindisi",
    CA: "Cagliari",
    CL: "Caltanissetta",
    CB: "Campobasso",
    CI: "Carbonia-Iglesias",
    CE: "Caserta",
    CT: "Catania",
    CZ: "Catanzaro",
    CH: "Chieti",
    CO: "Como",
    CR: "Cremona",
    CS: "Cosenza",
    CN: "Cuneo",
    EN: "Enna",
    FE: "Ferrara",
    FI: "Firenze",
    FG: "Foggia",
    FC: "Forlì-Cesena",
    FR: "Frosinone",
    GE: "Genova",
    GO: "Gorizia",
    GR: "Grosseto",
    IM: "Imperia",
    IS: "Isernia",
    SP: "La Spezia",
    LT: "Latina",
    LE: "Lecce",
    LC: "Lecco",
    LI: "Livorno",
    LO: "Lodi",
    LU: "Lucca",
    MB: "Monza e Brianza",
    MC: "Macerata",
    MN: "Mantova",
    MS: "Massa-Carrara",
    MT: "Matera",
    ME: "Messina",
    MI: "Milano",
    MO: "Modena",
    NA: "Napoli",
    NO: "Novara",
    NU: "Nuoro",
    OR: "Oristano",
    PD: "Padova",
    PA: "Palermo",
    PR: "Parma",
    PV: "Pavia",
    PG: "Perugia",
    PS: "Pesaro e Urbino",
    PE: "Pescara",
    PI: "Pisa",
    PT: "Pistoia",
    PN: "Pordenone",
    PZ: "Potenza",
    PO: "Prato",
    RA: "Ravenna",
    RC: "Reggio Calabria",
    RE: "Reggio Emilia",
    RI: "Rieti",
    RM: "Roma",
    RN: "Rimini",
    RO: "Rovigo",
    SA: "Salerno",
    SI: "Siena",
    SR: "Siracusa",
    SO: "Sondrio",
    SS: "Sassari",
    SV: "Savona",
    TA: "Taranto",
    TE: "Teramo",
    TN: "Trento",
    TO: "Torino",
    TP: "Trapani",
    TR: "Terni",
    TV: "Treviso",
    TS: "Trieste",
    UD: "Udine",
    VA: "Varese",
    VE: "Venezia",
    VB: "Verbania",
    VC: "Vercelli",
    VR: "Verona",
    VV: "Vibo Valentia",
    VT: "Viterbo",
  };
  return provinceTranslations[province.toUpperCase()] || province;
};
