export const SPORTS: { [key: string]: string } = {
  apnea: "Apnea",
  airsoft: "Airsoft",
  alpinism: "Alpinismo",
  climbing: "Arrampicata",
  sport_climbing: "Arrampicata sportiva",
  martial_arts: "Arti marziali",
  athletics: "Atletica",
  light_athletics: "Atletica leggera",
  heavy_athletics: "Atletica pesante",
  badminton: "Badminton",
  baseball: "Baseball",
  basketball: "Basket",
  beach_volley: "Beach volley",
  billiards: "Biliardo",
  boxing: "Boxe",
  brazilian_jiu_jitsu: "Brazilian Jiu Jitsu",
  football: "Calcio",
  futsal: "Calcio a 5",
  seven_a_side_football: "Calcio a 7",
  table_soccer: "Calciobalilla",
  callanetics: "Callanetica",
  canoeing: "Canoismo",
  rowing: "Canottaggio",
  cycling: "Ciclismo",
  cricket: "Cricket",
  curling: "Curling",
  dancing: "Danza",
  sport_dance: "Danza sportiva",
  equestrian: "Equitazione",
  e_sport: "ESport",
  fire_fit: "FireFit",
  fitness: "Fitness",
  american_football: "Football americano",
  footgolf: "FootGolf",
  gymnastics: "Ginnastica",
  gymnastics_on_the_apparatus: "Ginnastica agli attrezzi",
  artistic_gymnastics: "Ginnastica artistica",
  soft_gymnastics: "Ginnastica dolce",
  functional_gymnastics: "Ginnastica funzionale",
  postural_gymnastics: "Ginnastica posturale",
  rhythmic_gymnastics: "Ginnastica ritmica",
  motor_play: "Gioco motorio",
  golf: "Golf",
  grappling: "Grappling",
  hockey: "Hockey",
  horseball: "Horseball",
  diving: "Immersione",
  iron_man: "Ironman",
  judo: "Judo",
  karate: "Karate",
  kayak: "Kayak",
  kick_boxing: "Kick boxing",
  wrestling: "Lotta libera",
  mma: "MMA",
  mono_wheel: "Monorouta",
  motorcycle: "Motociclismo",
  motocross: "Motocross",
  mountain_bike: "Mountain bike",
  nordic_walking: "Nordic walking",
  swimming: "Nuoto",
  synchronized_swimming: "Nuoto sincronizzato",
  padel: "Padel",
  handball: "Pallamano",
  waterpolo: "Pallanuoto",
  volleyball: "Pallavolo",
  tambourine_ball: "Palla Tamburello",
  parkour: "Parkour",
  skating: "Pattinaggio",
  roller_skating: "Pattinaggio a rotelle",
  ice_skating: "Pattinaggio su ghiaccio",
  freediving: "Pesca in apnea",
  pilates: "Pilates",
  rugby: "Rugby",
  fencing: "Scherma",
  skiing: "Sci",
  cross_country_skiing: "Sci di fondo",
  skateboard: "Skateboard",
  snowboard: "Snowboard",
  weightlifting: "Sollevamento Pesi",
  softair: "Softair",
  softball: "Softball",
  squash: "Squash",
  step_and_tone: "Step and Tone",
  taekwondo: "Taekwondo",
  tai_chi_chuan: "Tai Chi Chuan",
  tennis: "Tennis",
  table_tennis: "Tennis Tavolo",
  triathlon: "Triathlon",
  archery: "Tiro con l'arco",
  dives: "Tuffi",
  ultimate_frisbee: "Ultimate frisbee",
  sailing: "Vela",
  wakeboard: "Wakeboard",
  waveboard: "Waveboard",
  yoga: "Yoga",
  baskin: "Baskin",
  karting: "Karting",
  vovinam: "Vovinam",
  calistenics: "Calistenics",
  aikido: "Aikido",
  equestrian_vaulting: "Volteggio Equestre",
  kettlebell: "Kettlebell",
  kung_fu: "Kung Fu",
  paragliding: "Parapendio",
  trekking: "Trekking",
  sport_fishing: "Pesca Sportiva",
  trail_running: "Trail running",
  savate: "Savate",
  wing_chun: "Wing Chun",
  bike_polo: "Bike Polo",
  windsurf: "Windsurf",
  sup: "Stand Up Paddle",
  waszp: "Waszp",
  running_skating: "Pattinaggio corsa",
  dodgeball: "Dodgeball",
  jujitsu: "Jujitsu",
  tug_of_war: "Tiro alla fune",
  aerobatics: "Acrobatica aerea",
  bowling: "Bowling",
  cheerleading: "Cheerleading",
  cheerability: "Cheerability",
  cheerdance: "Cheerdance",
  capoeira: "Capoeira",
  psychomotricity: "PsicomotricitÃ ",
  darts: "Freccette",
  kendo: "Kendo",
  iaido: "Iaido",
  jodo: "Jodo",
  teamgym: "TeamGym",
  music: "Musica",
  acrobatic_gymnastics: "Ginnastica acrobatica",
  naginata: "Naginata",
  orienteering: "Orienteering",
  beach_tennis: "Beach tennis",
  shooting: "Tiro a volo",
  target_shooting: "Tiro a segno",
  rafting: "Rafting",
  canyoning: "Torrentismo",
  motoring: "Automobilismo",
  classic_cars: "Auto d'epoca",
  ultralight_aviation: "Volo ultraleggero",
  bodybuilding: "Bodybuilding",
};
